### ISSUE TITLE
`bindNextTo` not updating value

### ISSUE THREAD

**Issue by ivanmoskalev** [ReactiveKit/ReactiveKit#10]
Subj. The problem is in the [implementation of `Observable`](https://github.com/ReactiveKit/ReactiveKit/blob/master/ReactiveKit/Observable/Observable.swift#L30-L48) – when `value` is set, it does send a `next` message, but a call to `next` doesn't set the value, just propagates it to child observers.

**Comment by srdanrasic** [comment]
Terrible. Thanks!

**Comment by srdanrasic** [comment]
Fix in v1.0.8.
