### ISSUE TITLE
Where did NoError go? 

### ISSUE THREAD

**Issue by iandundas** [ReactiveKit/ReactiveKit#104]
Whilst trying to make an `Operation<Void, NoError>`, it seems that the empty Error type `NoError` has been removed (unless I'm mistaken). Is there a replacement available - I can't seem to find it.

**Comment by srdanrasic** [comment]
Yes, it was removed, but it will be back in the next version. You can define it yourself until then. It was just an empty enum.

```swift
enum NoError {}
```

**Comment by iandundas** [comment]
Cool, thanks! 

(for anyone finding this: `enum NoError: ErrorType {}`)
