### ISSUE TITLE
Include of non-modular header inside framework module 'ReactiveKit.ReactiveKit'

### ISSUE THREAD

**Issue by app-buzz** [ReactiveKit/ReactiveKit#105]
Using cocoapods to install and get this build error.

<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/ReactiveKit-umbrella.h"
        ^
/Users/guywatson/Documents/RenderingDynamicData/Pods/Target Support Files/ReactiveKit/ReactiveKit-umbrella.h:3:9: note: in file included from /Users/guywatson/Documents/RenderingDynamicData/Pods/Target Support Files/ReactiveKit/ReactiveKit-umbrella.h:3:
#import "ReactiveKit.h"
        ^
/Users/guywatson/Documents/RenderingDynamicData/Pods/ReactiveKit/ReactiveKit/ReactiveKit.h:26:9: error: include of non-modular header inside framework module 'ReactiveKit.ReactiveKit'
#import <ReactiveKit/RKProtocolProxyBase.h>
        ^
<unknown>:0: error: could not build Objective-C module 'ReactiveKit'

**Comment by srdanrasic** [comment]
This happens is not using latest cocoapods.
