### ISSUE TITLE
StreamType Helpers

### ISSUE THREAD

**Issue by AnthonyMDev** [ReactiveKit/ReactiveKit#109]
I constantly find myself creating a bunch of helper functions in extensions on `StreamType`.

They are all really simple functions. For example:
- A function that transform a stream of `NSDate` into `String` using an `NSDateFormatter`
- A function `inverse()` that transforms a stream of `Bool` by returning it's opposite.

I would like to make these available to the public. My question is, are these helper functions appropriate for the main repo? Should I be making PRs for each of these?

My other option is to create a new CocoaPod of my own that includes all of these extensions. Or do you have a suggestion for a better way to release these?

Thanks

**Comment by srdanrasic** [comment]
Hey @AnthonyMDev, sorry for slow response.

I'd like to keep ReactiveKit as lightweight as possible. Bool inverse could get in, but I'd like to keep foundation types out of this.

**Comment by AnthonyMDev** [comment]
Okay no worries. I'll make my own extensions library. I may open source it separately from this pod if it becomes extensive enough.
