### ISSUE TITLE
Is is sensible to always deliver on main thread?

### ISSUE THREAD

**Issue by ivanmoskalev** [ReactiveKit/ReactiveKit#11]
Wouldn't it be more suitable to use main thread in the UIKit-library rather than the abstract one? Bindings can in fact be used outside the main thread for various reasons. 

For example, one can have several reusable and independent view models, which are composed to create a screen model. Those smaller models will likely use bindings for communication between each other, should they need it. Then, this communication can be performed off the main thread. But right now it will be scheduled on the main thread implicitly.

What I suggest is to force main thread scheduling in the UIKit extensions, where it seems quite sensible, and make immediate scheduling the implicit one for the ReactiveKit abstract library.

**Comment by srdanrasic** [comment]
Agreed, let's restrict implicit main execution context just to UI bindings.

Original goal was to simplify threading so that developer doesn't have to deal too much with it, but that goal should not be sacrificed by the restriction.

:+1:

**Comment by ivanmoskalev** [comment]
By the way, if we just add `ImmediateOnMain`-ish scheduling, it won't even break `throttle`.

**Comment by srdanrasic** [comment]
Just done that for ReactiveUIKit :) Now we can safely remove implicit context from here.

**Comment by ivanmoskalev** [comment]
:rocket:

**Comment by srdanrasic** [comment]
What do you think about implicit `ImmediateOnMain` for `observe`/`observeNext` methods. I feel that should stay. It would be too easy to make a mistake there.

**Comment by ivanmoskalev** [comment]
Yes, I think so too...
