### ISSUE TITLE
Compilation fails for Swift Package Manager

### ISSUE THREAD

**Issue by patrick-lind** [ReactiveKit/ReactiveKit#111]
If I pull down the current Master branch and run "swift build" in the repository I get a bunch of compile time errors. Things like:

/ReactiveKit/Sources/Subjects.swift:32:22: error: use of unresolved identifier 'NSRecursiveLock'
  private let lock = NSRecursiveLock(name: "PublishSubject")
                     ^~~~~~~~~~~~~~~

But if I open the project in Xcode 8 and compile, it works just fine. I'm using Xcode Version 8.0 (8A218a). It seems like its missing imports for Foundation or something like that. Anyone else experiencing the same thing?

**Comment by srdanrasic** [comment]
Yeah, I see it now... Let me add those imports.

**Comment by srdanrasic** [comment]
Thanks @patrick-lind for reporting this. I hope v3.0.0-beta3 now works with SPM.

**Comment by patrick-lind** [comment]
I can confirm that fixed it. Thanks!
