### ISSUE TITLE
bidirectionalBind() not working as expected

### ISSUE THREAD

**Issue by tonyarnold** [ReactiveKit/ReactiveKit#112]
I can't get `bidirectionalBind()` to work as expected. The values of bound Property instances don't seem to update.

I've put together a simple sample project to show the issue - just run the unit tests: https://github.com/tonyarnold/PropertyBindTest

Am I doing something wrong?

**Comment by srdanrasic** [comment]
Thanks @tonyarnold for reporting this. Please try beta4.

**Comment by tonyarnold** [comment]
😗 👌 

Works great now, thanks @srdanrasic!
