### ISSUE TITLE
Bond 5.0

### ISSUE THREAD

**Issue by iandundas** [ReactiveKit/ReactiveKit#113]
Does Bond 5.0 replace ReactiveUIKit?

**Comment by jechol** [comment]
@iandundas Right.

> Binding extensions provided by ReactiveUIKit framework are now provided by Bond. Just import Bond instead of ReactiveUIKit and change extension prefixes from r to bnd

in Readme.

**Comment by iandundas** [comment]
Thanks

**Comment by iandundas** [comment]
Ps I did not see that change coming
