### ISSUE TITLE
combineLatest, zip should provide default `combine`

### ISSUE THREAD

**Issue by jechol** [ReactiveKit/ReactiveKit#117]
99% times, we just want a tuple consisted of values from each signal.

So I want to replace

```swift
combineLatest(a, b, c, combine: { ($0, $1, $2) })
```

with

```swift
combineLatest(a, b, c)
```

And, when `combine: ` is really necessary like,

```swift
combineLatest(a, b, c, combine: { User(id: $0, name: $1, age: $2) })
```

it might be replaced by `map` and it seems more readable like,

```swift
combineLatest(a, b, c).map { User(id: $0, name: $1, age: $2) }
```

And it becomes more consistent  as `SignalProtocol.combineLatest(with: SignalProtocol)` returns a tuple of them.

How do you think?

**Comment by srdanrasic** [comment]
Hmm, you are right, but I would not replace them, rather just add another overload that defaults to tuple combination. This already exists for instance methods like

```swift
public func combineLatest<O: SignalProtocol>(with other: O) -> Signal<(Element, O.Element), Error>
public func combineLatest<O: SignalProtocol, U>(with other: O, combine: @escaping (Element, O.Element) -> U) -> Signal<U, Error>
```

so we just need to add additional overloads for stand-alone functions that default to those tuple combinations.  I guess all functions in `SignalProtocol+Arities.swift` should then have tuple variant.

**Comment by jechol** [comment]
Right, I was adding overloads as you said.

Just want to confirm that I understand the situation correctly.

Please add those overloads.

**Comment by srdanrasic** [comment]
I can add them later today. If you need them earlier feel free to do PR.

**Comment by jechol** [comment]
I'll do that.
