### ISSUE TITLE
Binding to property - signal never deallocated

### ISSUE THREAD

**Issue by AnthonyMDev** [ReactiveKit/ReactiveKit#119]
The current implementation of `bind` on `Property`:

````swift
  public func bind(signal: Signal<Value, NoError>) -> Disposable {
    return signal.take(until: disposeBag.deallocated).observe(with: on)
  }
````

This leaves the bound signal with a retain that is never removed. The use of `take` does stop the signal from sending events after the `Property` has been deallocated, but the `CompositeDisposable` created by `take` is never disposed of and the signal is sticks around. This results in signals that are never deallocated.

Should be be disposing of the signal observation in the `Property` binding function like this:

````swift
public func bind(signal: Signal<Value, NoError>) -> Disposable {
    let disposable = signal.take(until: disposeBag.deallocated).observe(with: on)
    disposable.disposeIn(disposeBag)
    return disposable
  }
````

Or is the flaw that the `take` function never disposes of its own signal when completed? 

Hope to have this fixed ASAP. :) Thoughts?

**Comment by AnthonyMDev** [comment]
The more I look at this, the more I think that the root of the issue is the `take(until:)` function. Because this function stops the signal from sending events, but the observations on it are never disposed, this can cause signals that stick around in memory, sending events to nothing forever. Unless I'm mistaken on how this functionality works.

I haven't been able to work out a good way to solve this yet though.

**Comment by srdanrasic** [comment]
Actually, problem is with `.observe(with: on)`. It's so subtile :) It retains `on` function which in turn retains self which is the Property. So property is actually never even deallocated and `disposeBag.deallocated`  is never even fired.

I'm releasing new beta with the fix. Thanks for reporting this!

**Comment by AnthonyMDev** [comment]
@srdanrasic You're a wizard! Thanks!

**Comment by srdanrasic** [comment]
Haha, no, I've just been burned on those stuff more than once :D
