### ISSUE TITLE
Two-way-binding?

### ISSUE THREAD

**Issue by marbetschar** [ReactiveKit/ReactiveKit#12]
Which would be the best approach to handle a two-way-binding by using ReactiveKit?

Also I've opened up a question on integrating CouchbaseLite with ReactiveKit on StackOverflow; but unfortunately I wasn't able to select the tag "ReactiveKit". So if you could help there too, this would be awesome!

http://stackoverflow.com/questions/33973446/how-to-implement-two-way-binding-with-swift

**Comment by srdanrasic** [comment]
Oh, right, we'll need someone with 1.5k reputation to create us a tag...  I answered your question there.

**Comment by marbetschar** [comment]
Thank you very much!! Feel free to close the issue here :)

**Comment by srdanrasic** [comment]
Hope it helps :)
