### ISSUE TITLE
ReactiveKit Compile Times

### ISSUE THREAD

**Issue by adenisonafifi** [ReactiveKit/ReactiveKit#121]
After moving to Swift 2.3 and Xcode 8 I have began experiencing horrendous build times. Investigated by profiling xcodebuild according to this guide: http://irace.me/swift-profiling, and I found ReactiveKit to be the largest culprit. Specifically:

`2870.1ms  Pods/ReactiveKit/Sources/CollectionProperty.swift:81:15 public func filter(previousIndexMap: [Int : Int], include: Collection.Generator.Element -> Bool) -> ([Int : Int], CollectionChangeset<Array<Self.Collection.Generator.Element>>?)`

`2590.3ms  Pods/ReactiveKit/Sources/CollectionProperty.swift:81:15 public func filter(previousIndexMap: [Int : Int], include: Collection.Generator.Element -> Bool) -> ([Int : Int], CollectionChangeset<Array<Self.Collection.Generator.Element>>?)`

`881.7ms Pods/ReactiveUIKit/Sources/UICollectionView.swift:54:15 public func bindTo(collectionView: UICollectionView, animated: Bool = default, createCell: (NSIndexPath, Element.Collection, UICollectionView) -> UICollectionViewCell) -> Disposable`

`877.3ms Pods/ReactiveUIKit/Sources/UICollectionView.swift:85:39 (closure)`

`743.6ms Pods/ReactiveUIKit/Sources/UICollectionView.swift:54:15 public func bindTo(collectionView: UICollectionView, animated: Bool = default, createCell: (NSIndexPath, Element.Collection, UICollectionView) -> UICollectionViewCell) -> Disposable`

738.9ms Pods/ReactiveUIKit/Sources/UICollectionView.swift:85:39 (closure)`

`716.2ms Pods/ReactiveUIKit/Sources/UITableView.swift:54:15  public func bindTo(tableView: UITableView, animated: Bool = default, createCell: (NSIndexPath, Element.Collection, UITableView) -> UITableViewCell) -> Disposable`

`715.3ms Pods/ReactiveUIKit/Sources/UITableView.swift:54:15  public func bindTo(tableView: UITableView, animated: Bool = default, createCell: (NSIndexPath, Element.Collection, UITableView) -> UITableViewCell) -> Disposable`

`712.6ms Pods/ReactiveUIKit/Sources/UITableView.swift:85:39  (closure)`

`711.8ms Pods/ReactiveUIKit/Sources/UITableView.swift:85:39  (closure)`

I will see if I can come up with a fix.

**Comment by srdanrasic** [comment]
Currently all efforts are on ReactiveKit 3 (+Bond 5) and Swift 3.

My guess is that it was caused by extensive use of generics. Implementation of v3 has been considerably simplified. Whole library now compiles in few seconds.

**Comment by adenisonafifi** [comment]
That sounds reasonable, I'll wait for ReactiveKit 3.

**Comment by srdanrasic** [comment]
ReactiveKit has been significantly refactored in v3 and compilation is much improved since the library is now very lightweight (~2k LOC).
