### ISSUE TITLE
Using RK in Extensions

### ISSUE THREAD

**Issue by akbsteam** [ReactiveKit/ReactiveKit#124]
I'd like to use RK in the iMessage app (extension) I'm building but I get the following:-

linking against a dylib which is not safe for use in application extensions: .... 

for both RK and Bond. 

Any ideas?

**Comment by srdanrasic** [comment]
Let me research that, I didn't try it before.

**Comment by akbsteam** [comment]
Looks like from quick tests its just a case of 

> set the target’s “Require Only App-Extension-Safe API” build setting to Yes

https://developer.apple.com/library/content/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html

Assuming the frameworks don't use anything not allowed in extensions?

**Comment by srdanrasic** [comment]
I think ReactiveKit is good to go. I can't think of any instance where Bond uses extension unsafe APIs, but I need to double check.

**Comment by akbsteam** [comment]
It seems its ok once the target is set

**Comment by srdanrasic** [comment]
Great to hear that! :)

**Comment by iandundas** [comment]
Did this get merged though? Still seeing the issue from Bond & ReactiveKit

**Comment by srdanrasic** [comment]
Isn't this the setting that you set on app extension target?


tir. 7. feb. 2017 kl. 16.29 skrev Ian Dundas <notifications@github.com>:

**Comment by iandundas** [comment]
I could definitely be mistaken, but AFAIK it asserts that this dependancy doesn't use extension-unsafe API calls. By default this is set to YES on a new app extension target, and linking this with ReactiveKit/Bond triggers a warning - I think ReactiveKit/Bond need to set that flag too.

For reference I searched around and a bunch of other libs have merged the same issue:

https://github.com/bignerdranch/CoreDataStack/issues/115
https://github.com/SnapKit/Masonry/pull/328
https://github.com/jmfieldman/Mortar/pull/11
https://github.com/Haneke/HanekeSwift/pull/253

<img width="461" alt="screen shot 2017-02-08 at 09 01 57" src="https://cloud.githubusercontent.com/assets/1131967/22730052/47d458be-eddd-11e6-9098-dc639d2268b3.png">
