### ISSUE TITLE
Public immutable Property

### ISSUE THREAD

**Issue by zdenektopic** [ReactiveKit/ReactiveKit#125]
Hello,

I am trying to figure out how to do with `ReactiveKit` publicly immutable property. Same with (Mutable)`ObservableArray` in bond.

**Comment by srdanrasic** [comment]
Property is now mutable. You can use AnyProperty to expose private property publicly:

```swift
private let _p = Property<Int>(0)

public var p: AnyProperty<Int> {
    return _p.readOnlyView
}
```

**Comment by zdenektopic** [comment]
Ok, thanks. What about MutableObservableArray?

**Comment by srdanrasic** [comment]
MutableObservableArray is a subclass of ObservableArray so you can do


```swift
private let _array = MutableObservableArray<Int>(0)

public var array: ObservableArray<Int> {
    return _array
}```
