### ISSUE TITLE
Sending a rControlEvent

### ISSUE THREAD

**Issue by Joebayld** [ReactiveKit/ReactiveKit#126]
I've migrated from Bond4 to Bond5 which now works with ReactiveKit. In my code, I override a NSTableView and send control events to the observers when an action happens (i.e.: selection changes). I'm not sure how to go about sending that event to the observers with AnyObject as an argument. 

In the prior version, this would work. 

```
    override func selectRowIndexes(_ indexes: IndexSet, byExtendingSelection extend: Bool) {
        super.selectRowIndexes(indexes, byExtendingSelection: extend)
        bnd_controlEvent.next("testObject") // sends "testObject" to all observers
        }
        
```

But I can't get this to work with rControlEvent. 
```
    override func selectRowIndexes(_ indexes: IndexSet, byExtendingSelection extend: Bool) {
        super.selectRowIndexes(indexes, byExtendingSelection: extend)
        rControlEvent.feedNext(into: "testObject")
        }
        
```
                
Thoughts?

**Comment by srdanrasic** [comment]
Maybe you could set `objectValue` on the table view and then do `sendAction(on mask: NSEventMask)` to send an event.
