### ISSUE TITLE
carthage update fails

### ISSUE THREAD

**Issue by toshi0383** [ReactiveKit/ReactiveKit#13]
```
 $ carthage update  
*** Fetching ReactiveFoundation
*** Fetching ReactiveUIKit
*** Fetching ReactiveKit
*** Checking out ReactiveKit at "v1.0.8"
*** Checking out ReactiveFoundation at "v1.0.4"
*** Checking out ReactiveUIKit at "v1.0.6"
*** xcodebuild output can be found in /var/folders/tr/3lftss053tqdh731cgt0w1p00000gn/T/carthage-xcodebuild.6LzfqB.log
Failed to discover shared schemes in project Quick.xcodeproj—either the project does not have any shared schemes, or xcodebuild never returned
```

The log file is empty.

```
$ xcodebuild -version
Xcode 7.1
Build version 7B91b
```

After removing Carthage/ dir, got same error.

**Comment by toshi0383** [comment]
Using `--platform iOS`

```
$ carthage update --platform ios
*** Cloning ReactiveFoundation
*** Cloning ReactiveUIKit
*** Cloning ReactiveKit
*** Checking out ReactiveFoundation at "v1.0.4"
*** Checking out ReactiveUIKit at "v1.0.6"
*** Checking out ReactiveKit at "v1.0.8"
*** xcodebuild output can be found in /var/folders/tr/3lftss053tqdh731cgt0w1p00000gn/T/carthage-xcodebuild.bOvVcK.log
Failed to discover shared schemes in project ReactiveKit.xcworkspace—either the project does not have any shared schemes, or xcodebuild never returned
```

**Comment by srdanrasic** [comment]
@toshi0383, do you have latest version of Carthage?

**Comment by toshi0383** [comment]
Yes, should be the latest. 
```
$ carthage version
0.10.0
```

**Comment by srdanrasic** [comment]
Oh I love Carthage. Looks like Cartfiles for dependencies were causing problems. I've removed them so I hope it will work now. Please try.

**Comment by ivanmoskalev** [comment]
Let's use CocoaPods primarily?

**Comment by Danappelxx** [comment]
@ivanmoskalev A lot of people use Carthage over cocoa pods so I don't think it's worth only using cocoa pods.

**Comment by ivanmoskalev** [comment]
@Danappelxx I think there is no trouble making the framework Carthage-supported even if we use another dependency manager as main :)

**Comment by Danappelxx** [comment]
I think the reason Carthage is being used in reactive kit is due to it being more stable and less involved. I personally think we should stick with it (at least, primarily).

**Comment by toshi0383** [comment]
```
** BUILD SUCCEEDED **
```

Thanks !

**Comment by srdanrasic** [comment]
@ivanmoskalev, I guess by "main" you mean dependency manager for "sub-frameworks" like ReactiveFoundation dependency on ReactiveKit? I've switched all that to git submodules :) Carthage honours git submodules and CocoaPods manages dependencies well so I think we should be good to go.
