### ISSUE TITLE
Remove `Safe` prefix.

### ISSUE THREAD

**Issue by jechol** [ReactiveKit/ReactiveKit#132]
I use `SafeXXX` almost 99% of times.

That `Safe` should be default.

How about prefixing `Unsafe` to default implementation, and leave out `Safe` from safe one.

I know this will be breaking change,
but for me, it just feels like find & replace which can be automated.

**Comment by srdanrasic** [comment]
I understand your feelings regarding this and I share them, but such breaking change would cause much pain, especially to other frameworks depending on ReactiveKit. Additionally, I'm not sure `UnsafeSignal` is the right way to go.

Many people just don't care and use `Signal<X, NoError>` and this change would force unnecessary changes to them. Also, prevalence of `Safe` might not be true for all scenarios. For example, I have a API client framework that works almost exclusively with `Signal<X, SomeError>`.

I'd say let's be patient and wait for Swift 4 that will hopefully introduce default generic arguments so will be able to define signal as `Signal<Element, Error: Swift.Error = NoError>` and use it either like `Signal<X>` or `Signal<X, SomeError>` where former defaults `Error` to `NoError`.

I'm even thinking about writing a proposal to Swift Evolution to make sure we get this feature.

**Comment by srdanrasic** [comment]
Unfortunately my proposal did not go through at the time as Swift core team did not find the feature significant enough to justify the time need to implement it. 

Thankfully they've been open to the idea so it will probably happen at one point - although I doubt we will see it before Swift 6 😢 

https://github.com/apple/swift-evolution/pull/591
