### ISSUE TITLE
ReactiveKit + Bond generates a segmentation fault 11

### ISSUE THREAD

**Issue by eMdOS** [ReactiveKit/ReactiveKit#135]
As README file says, I have added:

Cartfile:
```
github "ReactiveKit/ReactiveKit" ~> 3.2
github "ReactiveKit/Bond" ~> 6.0
```

Cartfile.resolved:
```
github "wokalski/Diff.swift" "0.4.2"
github "ReactiveKit/ReactiveKit" "v3.2.0"
github "ReactiveKit/Bond" "v6.0.0-beta.1"
```

Today I ran `carthage update` and I noticed `Cartfile.resolved` changed:
```
github "ReactiveKit/ReactiveKit" "v3.2.1"
github "ReactiveKit/Bond" "v5.0.0-beta9"
```

`Diff` disappeared, so I removed it from `link binary with libraries` and I started getting a `segmentation fault 11`. and I realized bond `v6.0.0-beta.1` tag is no more longer available.

**Comment by srdanrasic** [comment]
Damn, there are 6.0.0-beta.1, 6.0.0-beta.2 and 6.0.0-beta.3 tags, why are they not being picked up by Carthage. I added v6.0.0-beta.3 to fix it for now.

**Comment by srdanrasic** [comment]
Looking like Carthage does not yet support prereleases. 

https://github.com/Carthage/Carthage/issues/1707

You'll have to use `github "ReactiveKit/Bond" "6.0.0-beta.3"`.I'll update the docs. Thanks for reporting this.

**Comment by eMdOS** [comment]
Today I changed my `Cartfile` having something like this:
```
github "ReactiveKit/ReactiveKit" ~> 3.2
github "ReactiveKit/Bond" "bond-6"
```
... and it is working.

Today night, I'll try adding `github "ReactiveKit/Bond" "6.0.0-beta.3"`.

Thanks in advance.
