### ISSUE TITLE
Property silentUpdate with combineLatest

### ISSUE THREAD

**Issue by adenisonafifi** [ReactiveKit/ReactiveKit#137]
I noticed that while using Property's function:
```
  /// Change the underlying value withouth notifying the observers.
  public func silentUpdate(value: Value) {
    _value = value
  }
```

It does properly prevent notifying the observers, but without reading into the source I had expected that the silent update would be picked up by combineLatest.

Here is an example:

```
        let propertyA = Property<String>("Test")
        let propertyB = Property<Int>(0)

        combineLatest(propertyA, propertyB).observeNext { string, integer in
          // Expected Sequence:
          // ("Test", 0)
          // ("New Value", 1)

          // Actual Sequence:
          // ("Test", 0)
          // ("Test", 1)
        }

        propertyA.silentUpdate(value: "New Value")
        propertyB.next(1)
```

It does make sense after reading the source that combineLatest wouldn't receive the silent update, but it would be convenient to have a way to group the updates.

**Comment by srdanrasic** [comment]
All operators internally observe to source signal, so if the observer is not called, nothing will be received. Unfortunately there is nothing we can do.

I think you should see if it's possible for you to avoid using `silentUpdate` at all. I would not recommend using that except in very rare and extreme cases.
