### ISSUE TITLE
Queue.background -> DispatchQueue.global(qos: .background)?

### ISSUE THREAD

**Issue by iandundas** [ReactiveKit/ReactiveKit#138]
Just checking - is this the correct substitution?

Where we'd use `Queue.background.context` before, we now use something like `DispatchQueue.global(qos: .background).context`?

Cheers,

**Comment by srdanrasic** [comment]
That is correct. Also, most of the methods that accept execution contexts now have overload that accept dispatch queues so writing just `.global(qos: .background)` should work.

**Comment by iandundas** [comment]
Cool many thanks
