### ISSUE TITLE
zip() now requires all inputs to complete before completing

### ISSUE THREAD

**Issue by iandundas** [ReactiveKit/ReactiveKit#139]
Whilst updating from v2, I've found that `zip()` no longer completes until all inputs have completed. Previously the output stream would complete immediately whenever any input streams completed.

I just wanted to query this: given that `zip()` inherently requires all signals to be emitting in order to work (once one signal completes there can be no more events emitted), should we not complete at this point?

As an example, here's my use case:

`zip(taps, SafeSignal.sequence(steps)).map { _, step in return step}`

Previously when we'd reached the end of the `steps` sequence, the zip would complete, (`.completed` was a very useful event in this scenario). But now it doesn't complete and continues consuming tap events without outputting anything. I think the previous behaviour was more useful, and just wanted to get your take on it,

Cheers

**Comment by srdanrasic** [comment]
Good catch! This seems to be a bug.
