### ISSUE TITLE
Replay usage

### ISSUE THREAD

**Issue by iandundas** [ReactiveKit/ReactiveKit#141]
I'm trying to understand `.replay()` for my use-case

My use-case is the following:

```swift

protocol MyViewModelType{
    var becomeSelected: SafeSignal<Void> {get}
}

class MyViewModel: MyViewModelType{
    let becomeSelected: SafeSignal<Void>
    private let becomeSelectedSink = SafePublishSubject<Void>()
    
    private let bag = DisposeBag()
    
    init(){
        becomeSelected = becomeSelectedSink.toSignal()
        
        becomeSelectedSink.next()
    }
}

let viewmodel = MyViewModel()
viewmodel.becomeSelected.observeNext { (next) in
    print("Next: \(next)")
}
```

I want to hide the `SafePublishSubject` behind the `MyViewModelType` protocol, so that `.next` events can only be sent from inside `MyViewModel`, (and there's no temptation to do it from the ViewController).

The problem is that the observer in the example above does not receive the `.next` event, because it starts observing after `.next` is sent. So far so normal - this is where replay comes in.

I'd expect there to be something I could add here (relating to `replay`) which would solve this in one line, but I can't seem to find it. `.sharedReplay` doesn't have the result I'd expect (I don't receive the `.next` event in my observer above), and I don't want my public interface here to deal with `ConnectableSignal` etc.

I propose the following extension, but if this is already covered by another function do let me know 👍 : 

```swift
extension SignalProtocol {

  /// Connect to replay events (disposing in given bag) and deliver events on returned Signal
  public func connectedReplay(limit: Int = Int.max, bag: DisposeBagProtocol) -> Signal<Element, Error>{
    let replayer = self.replay(limit)
    replayer.connect().dispose(in: bag)
    return replayer.toSignal()
  }
}
```

So this would be used like so:

```swift
class MyViewModel: MyViewModelType{
    let becomeSelected: SafeSignal<Void>
    private let becomeSelectedSink = SafePublishSubject<Void>()
    
    private let bag = DisposeBag()
    
    init(){
        becomeSelected = becomeSelectedSink.connectedReplay(limit: 1, bag: bag)
        
        becomeSelectedSink.next()
    }
}

let viewmodel = MyViewModel()
viewmodel.becomeSelected.observeNext { (next) in
    print("Next: \(next)")
}
```

As used above, my observer does receive the `.next` event.

I'm using this quite a bit in my app - is it worth submitting a pull request or have I misunderstood some existing functionality 

Cheers

**Comment by iandundas** [comment]
(p.s. the `becomeSelected` use case is contrived for the example)

**Comment by iandundas** [comment]
(pre-emptive pull request)

**Comment by srdanrasic** [comment]
Hey @iandundas, there is also a SafeReplaySubject that you could use instead of SafePublishSubject :) Can you check if that solves the problem?

**Comment by iandundas** [comment]
Yep that works! Huzzah. I knew there'd be something ;)
