### ISSUE TITLE
Support Xcode 9

### ISSUE THREAD

**Issue by serieuxchat** [ReactiveKit/ReactiveKit#152]
I know that it's a bit early now, but being able to compile with Xcode 9 (and Swift 3.2) would be really cool (since code completion and the editor in general is SO much nicer in the new Xcode).

**Comment by srdanrasic** [comment]
Hey @serieuxchat, latest version should compile under Swift 4 (Xcode 9 beta 1) without any warnings. What errors are you getting?

I haven't tried with CocoaPods or Carthage though.

Plan is to support Swift 4 from early on. ReactiveKit should be working, but there are some issues with Bond which will be solved one way or another in the following days.

**Comment by serieuxchat** [comment]
Good point - let me double check if I am using the latest version.

I am using cocoapods and compiling with Swift 3.2 (not Swift 4).

**Comment by serieuxchat** [comment]
Updated to the latest version - compiles fine now!
But there are some issues in Bond (which should be easy to correct). I will close this issue and create one for Bond.

**Comment by srdanrasic** [comment]
Cool :)

We are tracking Bond issue here: https://github.com/ReactiveKit/Bond/issues/425
