### ISSUE TITLE
Binding twice a signal will cause manipulations  to trigger twice

### ISSUE THREAD

**Issue by angu** [ReactiveKit/ReactiveKit#154]
Hi, not sure if this is a bug or the expected behaviour, but If I bind twice the same signal manipulations made to the signal will be invoked twice.
Here is an example:

```
        let output1 = SafePublishSubject<Int>()
        let output2 = SafePublishSubject<Int>()
        let input = SafePublishSubject<Int>()
        let mapped = input.map { number -> Int in
            print("map(:) - \(number) - \(Date())")
            return number
        }
        
        mapped.bind(to: output1)
        mapped.bind(to: output2)
        
        input.next(1)
```

will output this:
```     
       map(:) - 1 - 2017-06-19 11:31:22 +0000
       map(:) - 1 - 2017-06-19 11:31:22 +0000
```

Am I supposed to be able to bind twice the same signal?

The current workaround I have found is instead of creating a signal to bind the map function to another publishsubject and then bind that to the outputs.

**Comment by srdanrasic** [comment]
Yes, this is expected behaviour. If you want to replace the binding, you can dispose the old one by keeping a disposable and dispose it before making another binding. Check out readme on disposables :)
