### ISSUE TITLE
DynamicSubject dual binding

### ISSUE THREAD

**Issue by sgousseauofficiel** [ReactiveKit/ReactiveKit#156]
Hello,

I've tried to make a dual binding between a text field and a DynamicSubject but it does not behave as in your test cases samples.

My dynamic subjects are done with the NSObject extension .keyPath method:

```swift

public var organizerDetail: String?

///Sends values when KVO see changes to the "orgamizerDetail" property (store institution id)
    public var dynamicOrganizerDetail: DynamicSubject<Optional<String>> {
        return self.reactive.keyPath(SerializationKeys.organizerDetail, ofType: Optional<String>.self)
    }
```

Here is how i have to write dual binding to get it working:

```swift
filter.dynamicOrganizerDetail.bind(to: self.filterValueTextField.reactive.text).dispose(in: self.bag)
            self.filterValueTextField.reactive.text.bind(to: filter.dynamicOrganizerDetail).dispose(in: self.bag)
```

Could you please explain to me why I'm not able to get the bidirectional operator working in this sample?

**Comment by srdanrasic** [comment]
Hi! 

How are you trying to bidirectionally bind and what exactly is the problem?

**Comment by sgousseauofficiel** [comment]
Hi, thanks for your answer.

here is the bi-directional that i can't manage to get working:
```swift
self.filterValueTextField.reactive.text.bidirectionalBind(to: self.viewModel.creatingEvent.dynamicTitle).dispose(in: self.bag)
```
Here is the manual binding that works:
```swift
self.viewModel.creatingEvent.dynamicTitle.bind(to: self.filterValueTextField.reactive.text).dispose(in: self.bag)
        self.filterValueTextField.reactive.text.bind(to: self.viewModel.creatingEvent.dynamicTitle).dispose(in: self.bag)
```

dynamicTitle : 
```swift
///Sends values when KVO see changes to the "title" property
    public var dynamicTitle: DynamicSubject<Optional<String>> {
        return self.reactive.keyPath("title", ofType: Optional<String>.self)
    }
```

**Comment by srdanrasic** [comment]
In what way does it not work? Does it not compile? Does it not get updated?

**Comment by sgousseauofficiel** [comment]
Yes  this works, but if you modify a.title, your textfield should receive the value and in my exemple it dont.

**Comment by sgousseauofficiel** [comment]
well, im seeing that i did not use the dynamic keyword, is it necessary ?

**Comment by srdanrasic** [comment]
`dynamic` is necessary to get KVO working in Swift :)

**Comment by sgousseauofficiel** [comment]
Ok, i will try setting my variables to dynamic and let you know soon.

Thank you, see you soon.
