### ISSUE TITLE
Handling error in composition

### ISSUE THREAD

**Issue by ramirez** [ReactiveKit/ReactiveKit#16]
Hi,

I was checking the example in the documentation about composing operations. What I can't figure out is how to handle errors. Is it possible to have one common error handler for the whole chain of composed operations? Ideally, this handler should be called if any of the operations in the chain fails.

Thx,

LR

**Comment by srdanrasic** [comment]
Hi @ramirez,

You can use `on` methods to catch error. 

```swift
authenticate(username: ..., password: ...)
  .flatMap(.Latest) { token in
    return fetchCurrentUser(token)
  }
  .on(failure: { error in
    print(error)
  })
  .observeNext { user in
    print("Authenticated as \(user.fullname).")
  }
```

It will catch error from any of the operations of the composition.

**Comment by srdanrasic** [comment]
If you wish to really handle it (by providing alternative results), use `flatMapError`: 

```swift
authenticate(username: ..., password: ...)
  .flatMap(.Latest) { token in
    return fetchCurrentUser(token)
  }
  .flatMapError { error in
    return Operation.succeeded(User.Anonymous)
  }
  .observeNext { user in
    print("Authenticated as \(user.fullname).")
  }
```

Closure passed to `flatMapError` when the composition generates any error. Your task is to provide operation that provides alternative results.

**Comment by ramirez** [comment]
Cool. I'll give it a shot and if you want I can try to add this hints to the documentation.

**Comment by srdanrasic** [comment]
Thanks @ramirez, if you get free time, feel free to do it, no pressure though.

**Comment by nayzak** [comment]
I asked similar [question on SO](http://stackoverflow.com/questions/35329031/how-to-properly-chain-several-operations-with-error-handling-and-branching-using). Could you look at it? :)
