### ISSUE TITLE
ld: library not found for -lnmea-universal

### ISSUE THREAD

**Issue by ianbroad** [ReactiveKit/ReactiveKit#162]
I pulled down a coworker's repo, and when I try to build the app I get the following error:

ld: library not found for -lnmea-universal

I tried redoing pod install, but it didn't help.

Any idea how to fix this error?

**Comment by srdanrasic** [comment]
Hey, that does not seem to be related to ReactiveKit.  

That being said, looks like Xcode can’t find nmea-universal library so you might want to search for that file and make sure library search paths are correctly configured in build settings.
