### ISSUE TITLE
Observable - declaration operators

### ISSUE THREAD

**Issue by zdenektopic** [ReactiveKit/ReactiveKit#17]
So I kinda did not like the way properties are being set in class. Having to say it is `Observable<String?>`.

What about introduing simple operator:
```
class SomeObject {
    
    var val: Bool
    
    init(val: Bool) {
        self.val = val
    }
    
}

prefix operator § {}
prefix operator §! {}
prefix operator §? {}

prefix func § <T: Any> (type: T) -> Observable<T> {
    return Observable<T>()
}

prefix func §! <T: Any> (type: T!) -> Observable<T!> {
    return Observable<T!>()
}

prefix func §? <T: Any> (type: T?) -> Observable<T?> {
    return Observable<T?>()
}

let some = §34
let other = §?"Some string"
let yetAnother = §!SomeObject(val: false)
```

Do you thing it is overkill that would cause just confusing or it is actually something that makes sense?
I did not figure out how to do it in type definition of the property. Same could apply to setting of observable.

**Comment by srdanrasic** [comment]
I feel that would scare to much users :) But you can always have that in your project. As long as you're consistent it should be fine.
