### ISSUE TITLE
[Swift 4] Missing argument when using PublishSubject<Void, NoError>

### ISSUE THREAD

**Issue by rsaarloos** [ReactiveKit/ReactiveKit#171]
Hi,

I'm currently busy with a migration to Swift 4.0. We are using in multiple locations the following typed signals:

```swift
let example = PublishSubject<Void, NoError>()
```

When compiling in XCode 9 with Swift 4.0 the compiler complains when this signal is called as such:
```swift
example.next()
```
It would return the following error: _"Missing argument for parameter #1 in call"_

A way to resolve this would be to define it as such, but this is of course not the desired way
```swift
example.next(())
```

What would be the correct way to resolve this?

**Comment by frankschlegel** [comment]
I'm currently migrating our project to Swift 4 and am getting the same error.
What's also curious is that passing `.next(Void)` also doesn't work ("passing too many arguments"…).
