### ISSUE TITLE
Equivalent of Rx switchMap?

### ISSUE THREAD

**Issue by svachmic** [ReactiveKit/ReactiveKit#176]
Hi!

I was wondering, after having spent some time with RxKotlin/RxJava - how can I implement similar behavior in ReactiveKit to Rx's **switchMap**? Something along the lines of:

```
myButton.reactive.tap
        .switchMap { apiCall() }
        .observeNext{ result in print(result) }
        .dispose(in: bag)
```

Is there a way to make this in ReactiveKit and also have it **a)** thread safe and **b)** not leaking?

Thanks a lot! 🍻

**Comment by srdanrasic** [comment]
Hey, the method is called `flatMapLatest` in ReactiveKit. Sorry for the slow reply.

**Comment by svachmic** [comment]
Perfect, thanks a lot!
