### ISSUE TITLE
Calling textField.becomeFirstResponder doesn't work when I call any ReactiveKit observer on that textfield.

### ISSUE THREAD

**Issue by EssamEmad** [ReactiveKit/ReactiveKit#180]
I have a sequence of textfields that I want the user to navigate through i.e: when they click next in the keyboard in one textfield they'd go to the next one. I also bind, in viewDidLoad, each of the textfields to its corresponding field in the model. Here's my implementation of the textFieldShouldReturn delegate method to make the next textfield the first responder:

```swift
func textFieldShouldReturn(_ textField: UITextField) -> Bool {
   let tag = textField.tag
    if let tf = self.view.viewWithTag(tag + 1) as? UITextField {
            tf.becomeFirstResponder()
            
        }
}
````
If I didn't observe the textfield's text property or bind them to the model the logic would work correctly. However, if I used the following code to bind the text to the model, the text field that is to become first responder would become the first responder for a couple of milliseconds then the keyboard would be dropped, the textfield wouldn't be in edit mode, and textFieldDidEndEditing would be called.

```swift
profile.firstName.bidirectionalBind(to: firstName.reactive.text)
 profile.lastName.bidirectionalBind(to: lastName.reactive.text)
profile.email.bidirectionalBind(to: email.reactive.text)
profile.password.bidirectionalBind(to: password.reactive.text)
profile.passwordConfirmation.bidirectionalBind(to: passwordConfirmation.reactive.text)
```

Interestingly enough I tried the solution to the same problem in a different reactive library [here](https://github.com/ReactiveX/RxSwift/issues/392) and it worked. but this is just a hack. [Here's](https://stackoverflow.com/a/48705691/4504604) my stackoverflow answer with the updated code.

I am submitting the issue as this is still a bug, and the hack I have made is not a proper solution.

**Comment by srdanrasic** [comment]
Unfortunately this seems the issue in UIKit, as explained in the Rx thread. I don't think we can do much to fix this on our side.

**Comment by EssamEmad** [comment]
Thanks for your response. However, it would be great if you can mention the solution/hack in the readme, as I spent too much time debugging this. This would be the case in common issues as [this](https://github.com/DeclarativeHub/Bond/issues/353).
