### ISSUE TITLE
Reactive Kit : Sample Application

### ISSUE THREAD

**Issue by fazilakhter** [ReactiveKit/ReactiveKit#19]
Hey guys , 
is there any sample application which use all of features of this kit ? 
that would be nice if we can have this in this code base. 

Thanks
Fazeel

**Comment by srdanrasic** [comment]
Hi @fazilakhter,

Thanks for the feedback. We don't have yet, but I'm working on one.

**Comment by fazilakhter** [comment]
Cool good stuff , really like this , as i am new into Reactive Stuff so would be great :) , but its way easy then CocoaReact which i have seen so far.

**Comment by ivanmoskalev** [comment]
@srdanrasic BTW, I was going to write a little article on FRP w/ ReactiveKit, with special regards to testing and reusability. So I will be making an example app too.

**Comment by srdanrasic** [comment]
Hi @ivanmoskalev, great, the more examples the better :)

**Comment by ramirez** [comment]
@ivanmoskalev : that sounds really cool. Looking forward to read that!

**Comment by balazsnemeth** [comment]
+1

**Comment by ppult-gini** [comment]
+1

**Comment by sergigracia** [comment]
+ 1

**Comment by limfinity** [comment]
+1

**Comment by sohooo** [comment]
There's a RayWenderlich tutorial called "Bond Tutorial: Bindings in Swift". I recreated the demo app from the tutorial (fetching images from 500px), swapping out Bond in favor of ReactiveKit to get a feel for the the changes.

Check out the repo: https://github.com/sohooo/BindingWithReactiveKit

**Comment by srdanrasic** [comment]
I've finally managed to get some free time to do this. You can find the demo app here: https://github.com/ReactiveKit/ReactiveGitter
