### ISSUE TITLE
Improve unit tests coverage

### ISSUE THREAD

**Issue by srdanrasic** [ReactiveKit/ReactiveKit#2]
Tests are currently written using Quick. We use carthage (`--no-build --use-submodules`) as the dependency manager, but I'm not sure about that - it still has too many issues.

After you clone the repo do `git submodule update --init`. It should also be possible to do `carthage bootstrap --no-build --use-submodules` instead, but that usually fails for me.

Use Xcode workspace file.

**Comment by ivanmoskalev** [comment]
I'll try to sort it out and will submit a PR where we can discuss implementation details :)
