### ISSUE TITLE
Turning observers on and off

### ISSUE THREAD

**Issue by ramirez** [ReactiveKit/ReactiveKit#21]
Hi,

 I'm observing a Stream and I would like to ignore the events while I change some other stuff in my model, and than start reacting again. Is it possible to pause or ignore the events of an observer for a while and then turn it on again, without having to dispose and recreate the observer?

Thx!

LEo

**Comment by srdanrasic** [comment]
Hi @ramirez, check out v1.1.0: https://github.com/ReactiveKit/ReactiveKit/releases/tag/v1.1.0

I added operator `pausable` that can make pausable stream that is controlled by a stream of booleans.

```swift
    let enabled = Observable(true)

    let a = Operation/Observable...

    a.pausable(enabled).observe { event in
      print(event)
    }
```

**Comment by ramirez** [comment]
Brilliant! Just what I needed :-)
