### ISSUE TITLE
Plans to implement a collect() like function from RAC?

### ISSUE THREAD

**Issue by DanielRakh** [ReactiveKit/ReactiveKit#23]
From the RAC documentation: 
> The collect operator is used to aggregate a event stream’s values into a single array value. Note that the final value is only sent after the input stream completes.

Any ideas on how one would accomplish that right now? 

Basically, say there's a situation where you need to make many network calls, which if I'm correct would each be wrapped in an Operation. Say you would like to gather all of the "nexts" from each respective operation and proceed only when all of the operations have ended. How would one do that right now?

**Comment by srdanrasic** [comment]
I'll add that.

**Comment by DanielRakh** [comment]
Awesome. Thank you!

**Comment by srdanrasic** [comment]
Hi @DanielRakh, check out v1.1.0: https://github.com/ReactiveKit/ReactiveKit/releases/tag/v1.1.0

**Comment by DanielRakh** [comment]
Great! Thanks.

**Comment by creister** [comment]
Hi, does anyone have an example of how to use this? I have two network requests that each return an operation, when they are complete they send .Next(value) and .Success. How would I combine them so I proceed only after both have completed?
```swift
func fetchImage(url: NSURL) -> Operation<UIImage, NSError> {
    return Operation { observer in
      let request = Alamofire.request(.GET, url).response { request, response, data, error in
        if let error = error {
          observer.failure(error)
        } else {
          observer.next(UIImage(data: data!)!)
          observer.success()
        }
      }
      return BlockDisposable {
        request.cancel()
      }
    }
  }

  func fetchData(url: NSURL) -> Operation<NSData, NSError> {
    return Operation { observer in
      let request = Alamofire.request(.GET, url).response { request, response, data, error in
        if let error = error {
          observer.failure(error)
        } else {
          observer.next(data!)
          observer.success()
        }
      }
      return BlockDisposable {
        request.cancel()
      }
    }
  }

  func fetchImageAndData() {
    // TODO: make 2 network requests and only proceed after both return success, or fail if either fails
  }
```

**Comment by srdanrasic** [comment]
You can try with zip operator:

```swift
func fetchImageAndData() -> Observable<(UIImage, NSData), NSError> {
    return zip(fetchImage(...), fetchData(...))
}
```

It send next pair when both operations send their next.
