### ISSUE TITLE
 Feature Request - Silent Update

### ISSUE THREAD

**Issue by AnthonyMDev** [ReactiveKit/ReactiveKit#26]
As per the discussion in ReactiveKit/ReactiveUIKit#5, a feature for silently updating the value of an `Observable` should be added.

This is useful in many scenarios, including bi-directional binding of multiple dependent values and updating the datasource for a `UICollectionView` when an item has been moved.

**Comment by AnthonyMDev** [comment]
Here is my proposal for implementing this on `Observable`

public final class Observable<Value>: ActiveStream<Value>, ObservableType {
  
  private var _value: Value
  
  public var value: Value {
    get {
      return _value
    }
    set {
      _value = newValue
      super.next(newValue)
    }
  }

  public init(_ value: Value) {
    self._value = value
    super.init()
  }

  public override func next(event: Value) {
    self.value = event
  }

  public override func observe(on context: ExecutionContext? = ImmediateOnMainExecutionContext, observer: Observer) -> DisposableType {
    let disposable = super.observe(on: context, observer: observer)
    observer(value)
    return disposable
  }
  
  public func silentUpdate(value: Value) {
    self._value = value
  }
  
}

@srdanrasic What do you think of this method? Should this be implemented on `ActiveStream` instead? What other stream types need to have a `silentUpdate()` method?

**Comment by srdanrasic** [comment]
@AnthonyMDev, I think it's good how you implemented it. I added something similar to ObservableCollection - it turned out to be very simple :) 

No need to add it to ActiveStream as that one has no concept of current value.

I've released this in v1.1.2.
