### ISSUE TITLE
performDiff for replace in obsrvable collections

### ISSUE THREAD

**Issue by ramirez** [ReactiveKit/ReactiveKit#29]
Hi,

I'm trying to use 
    myArray.replace(myNewArray, performDiff: true)

but the results doesn't seem to be right. I get in the inserts and deletes array what seems to be the indexes of the replaced elements:

    Collection before:: [36, 37]
    Collection after:: [43, 44]
    ObservableCollectionEvent<Array<Int>>(collection: [43, 44], inserts: [0, 1], deletes: [0, 1], updates: [])

Am I doing something wrong?

Thx!

LEo

**Comment by srdanrasic** [comment]
This is now part of Bond framework.
