### ISSUE TITLE
collectionView bounded to observableArray not updating after

### ISSUE THREAD

**Issue by ramirez** [ReactiveKit/ReactiveKit#31]
Hi,

I have a CollectionView bound to an observable array, and I'm removing one element from the observable array:

    myObservableArray.removeAtIndex(index.item)

but after doing that, contrary to what I would expect, the number of elements in the observable array is different to the number of elements in the collection:

    print("-->", myObservableArray.count, myCollectionView.numberOfItemsInSection(0))

    -->  2  3

Shouldn't both values be the same?

**Comment by ramirez** [comment]
Any clues?

**Comment by srdanrasic** [comment]
This is now part of Bond framework.
