### ISSUE TITLE
Simple example on rValueForKeyPath?

### ISSUE THREAD

**Issue by nopctoday** [ReactiveKit/ReactiveKit#32]
From what I understand is that `rValueForKeyPath` is an NSObject extension to observe property changes? I have tried a few different ways to observe but so far I haven't been abel to get the observe events to fire properly

    class SometViewModel{

    var testObj= TestClass()
    init(){
        testObj.test = "hello"
        
        delay(3){  //a delay timer
            self.testObj.test = "hello2"
        }

        testObj.rValueForKeyPath("test").observe{(value: String?) in
            print("Received: \(value)")
        }
        
    }
    
    class TestClass:NSObject{
        dynamic var test:String=""
    }
    }

**Comment by frankschlegel** [comment]
I think the problem is, that you don't retain the `Disposable` created by your KVO observer. From the ReadMe:

> Observing KVO-observable will be active as long as the returned disposable is alive. Make sure you store the disposable when using observe method on KVO-observable.

So what you could do is to either assign the `Disposable` returned by the `observe` call to a property, or create a `DisposeBag` and store it inside.

So this might work:
```
class SometViewModel{

var testObj= TestClass()
let disposeBag = DisposeBag()
init(){
    testObj.test = "hello"

    delay(3){  //a delay timer
        self.testObj.test = "hello2"
    }

    testObj.rValueForKeyPath("test").observe{(value: String?) in
        print("Received: \(value)")
    }.disposeIn(self.disposeBag)

}

deinit {
    // not sure if that's needed, might happen automatically when disposeBag is released
    self.disposeBag.dispose()
}

class TestClass:NSObject{
    dynamic var test:String=""
}
}
```
