### ISSUE TITLE
Removing from an observable collection results in a crash

### ISSUE THREAD

**Issue by esavantsi** [ReactiveKit/ReactiveKit#33]
The error occurs when the ObservableCollection is sorted

The bug can be reproduced with the following code:
```
var collection = ObservableCollection([1, 3, 2, 5])
var sorted = collection.sort { $0 < $1 }
while(collection.count > 1) {
  collection.removeLast()
}
```

The error happens in ObservableCollectionEvent.swift at line 106: let newDeletes = deletes.map { sortMap[$0]! }
fatal error: unexpectedly found nil while unwrapping an Optional value

Values of the variables when the error occurs:
sortMap: [0: 0, 2: 1, 1: 2]
inserts: []
deletes: [3]
updates: []

The error seems to be that the value to be removed is already removed from the sortMap and is still tried to find from there. Therefore, this issue occurs always when removing the last element of the ObservableCollection when there's a collection derived from it.

**Comment by srdanrasic** [comment]
Fixed in v2. Thanks!
