### ISSUE TITLE
Would an Event class make sense?

### ISSUE THREAD

**Issue by frankschlegel** [ReactiveKit/ReactiveKit#34]
I'm currently writing an iOS app using the view-model pattern realized with ReactiveKit (formerly Bond). For some scenarios I would like to have simple events I can observe and trigger—basically `Observable`s without the value.

I'm currently using `ActiveStream`s for that and call `next` for triggering them. But that doesn't feel right. Would it be a good idea to introduce an `Event` class with a `trigger` method? It might simply be a subclass of `ActiveStream` and call `self.next()` on `trigger`, but the naming would be much more descriptive.

Now, does it even make sense to have such a "pure" event type? I'm kinda new to reactive programming and don't know if that fits the pattern.

**Comment by tonyarnold** [comment]
Yeah, I have need of the same thing. I tried using an `Operation<Void, NoError>`, but couldn't work out how to initialise one that does nothing.

**Comment by frankschlegel** [comment]
Hmm... I think operations serve a different purpose (more for asynchronous tasks). I want a simple thing I can trigger that doesn't have a storage for the last value.

By the way, if you want to have multiple generic parameters you can use tuples for that: `Operation<(Type1, Type2)>`.

**Comment by srdanrasic** [comment]
`Operation<Void, NoError>` and `Stream<Void>` should be valid constructs, however I see there might be some issues with that at the moment. I'm working on an upgrade these days so I'll look into this too.

**Comment by tonyarnold** [comment]
@frankschlegel that's basically what I want, too. 

@srdanrasic you're a legend, thanks!

**Comment by srdanrasic** [comment]
Implemented in v2.
