### ISSUE TITLE
How to use StreamType sample()?

### ISSUE THREAD

**Issue by tonyarnold** [ReactiveKit/ReactiveKit#35]
I'm having a bit of trouble getting StreamType's `sample()` function to work — it fires once, then never again. What do I need to retain? The disposable or the operation? Thanks!

**Comment by tonyarnold** [comment]
My use case is that I'm trying to poll the result of an Operation once every `x` seconds.

**Comment by ramirez** [comment]
Hi,

Can you post some code so we can check what are you trying?

cheers,

LEo

**Comment by tonyarnold** [comment]
I have an Operation that I'm trying to sample once every few seconds:

```swift
myOperationFunction(someParam)
    .sample(0.5, on: Queue.main)
    .observe { event in
          print("Hello: \(event)")
    }
```

**Comment by ramirez** [comment]
is your operation producing a stream that can be sampled? If it produces only one next and then succeeds then your observer will only see that, I'd guess.

**Comment by tonyarnold** [comment]
Yeah, no, I think I'm off base about the function of this function. I thought that it would retrieve the latest value from a signal by polling once every x seconds (similar to `RACSignal`'s `interval:` method). I guess it does something entirely different.
