### ISSUE TITLE
distinctOptional do not send first "nil" value

### ISSUE THREAD

**Issue by volodg** [ReactiveKit/ReactiveKit#36]
Example:

        let observable = Observable<Int?>(nil)
        observable.distinctOptional().observe { (value) -> () in
            print("distinctOptional: \(value)")
        }

Prints nothing (((

**Comment by chrisvxd** [comment]
Is this a bug or is this expected behaviour when using distinctOptional? Would love to see some documentation around it.

**Comment by srdanrasic** [comment]
Fixed in v2. Note that v2 is still in beta.
