### ISSUE TITLE
Exponential and Fixed Backoff For the Operation Retry method

### ISSUE THREAD

**Issue by payparr** [ReactiveKit/ReactiveKit#37]
Having exponential and fixed backoff for the operation and retry method on Operation would be very useful. One way of doing it would be the following:

`` enum Backoff {
    case Exponential(Double) 
    case Fixed(Double)
    case None
}
``

 `` public func retry(var count: Int) -> Operation<Value, Error>  ``
would become
`` public func retry(var count: Int, backoff : Backoff  = .None) -> Operation<Value, Error>``

I can implement this if need be.

**Comment by srdanrasic** [comment]
It would be interesting PR :)
