### ISSUE TITLE
How to merge a bunch of Streams into a single Stream of the last changed value from any?

### ISSUE THREAD

**Issue by iandundas** [ReactiveKit/ReactiveKit#39]
Hi - I can't seem to find a merge function (as in [here](http://rxmarbles.com/#merge)) for Streams, but maybe I'm thinking about it wrong:

Say I have a bunch of streams which send UIColor events. I'm interested in the latest value coming from any of them, I don't care which Stream it is, only the value sent most recently.

```   
        let streamA: Stream<UIColor> ...
        let streamB: Stream<UIColor> ...
        let streamC: Stream<UIColor> ...
        let streamC: Stream<UIColor> ...
        let streamE: Stream<UIColor> ...
```

How would can I combine these streams together in a way that would achieve that? I have an inkling that it would involve a flatMap of type `StreamFlatMapStrategy.Merge`, but the transform block for that is of type: `<(UIColor, UIColor, UIColor, UIColor, UIColor) -> StreamType`, i.e. all the UIColor values together, where it's unclear which one changed.

Thanks in advance,

**Comment by srdanrasic** [comment]
I'll need to add this to ReactiveKit, but would be very simple function. Here, you can define it in your project unit I add it here.

```swift
public func merge<S: StreamType>(streams: [S]) -> Stream<S.Event> {
  return Stream { observer in
    let compositeDisposable = CompositeDisposable()
    for stream in streams {
      compositeDisposable += stream.observe(on: nil) { event in
        observer(event)
      }
    }
    return compositeDisposable
  }
}
```

You can then do:

```swift
let anyColor = merge([streamA, streamB, streamC...])
```

**Comment by iandundas** [comment]
Awesome - thanks man, I'll use that.
