### ISSUE TITLE
Leaks

### ISSUE THREAD

**Issue by ramirez** [ReactiveKit/ReactiveKit#42]
Hi,

I have been working on an application for a while using reactive kit and today I notice that my app has a lot of memory leaks. As it seems, probably coming from the use of observable vars and collection. They seem to creating a lot of retain cycles all the time. Can somebody give me some advice on how to avoid retain cycles while using ReactiveKit and how to break them once they appear? I am little out of clues here, as I tried several different things.

Thanks.

L.

PS: It seems like the development of ReactiveKit has slowed down or come to a stop. Is it still being developed?

**Comment by srdanrasic** [comment]
Hi @ramirez - yeah, a bit slowed down lately but I plan to continue as soon as I get some time.

Regarding leaks, be aware of closures, because everything you use in them gets retained. For example, observing like this: 

```swift
let name = Observable<String>("...")
...
name.observe { name in
   self.nameLabel.text = name
}
```

will cause leak because you have a retain cycle: self retains name and name retain self. In such cases it's best to use bindings. Otherwise use `[weak self]`. Disposing the observation will also break the cycle.

Same applies for transformation closures. The code

```swift
name.map { self.someFunction($0) }
```

will also capture self, and if self is holding the name, you'll have a cycle.

**Comment by ramirez** [comment]
Thanks for the quick reply. I'm more than happy to help if you need some coding hands :-)

As for my code, I'm checking it for closures retaining self, and I have managed to kill some of the cycles. I'm getting a lot of objects of class "RecursiveLock" retained, and I haven't been able to trace those. 

You wrote:
> In such cases it's best to use bindings.
 I'm not sure if I get what you mean with "use bindings" here. Can you give me an example?

Thanks again for the great Kit!

LEo

**Comment by srdanrasic** [comment]
RecursiveLocks are used by Disposables and Observables to ensure thread correctness. They should not outlive Disposables and Observables though. You probably have various Disposables and Observables alive - can you check that? Once those are destroyed, RecursiveLocks should also be gone.

Thanks for the offer :) I'll know more when I continue. First, I'll do some cleanup and add inline documentation. After that I might add some new stuff, but not too much as I want to keep the framework simple.

**Comment by ramirez** [comment]
Hi,

after making most of my captured self weak and trying some other stuff, I finally removed a couple of uses of ```retry``` that I had in my application and Instruments stopped showing cycles. Could it that be retry is causing retain cycles?


Cheers,

LEo

**Comment by srdanrasic** [comment]
I think you're right. There was a leak in the retry method. Should be fixed now in v1.1.3. Thanks :)

**Comment by ramirez** [comment]
Brilliant! Thanks to you!

LEo

**Comment by ramirez** [comment]
Hi. 

I also noticed a ```[weak self]``` is also wise when binding an observable collection to a collection view using ```bindTo(<UICollectionView:Bool:RKCollectionViewProxyDataSource?: (NSIndexPath:[Int]:UICollectionView) -> UICollectionViewCell)```.

Cheers,

LEo
