### ISSUE TITLE
Implement operators on Stream which currently exist only on Operation

### ISSUE THREAD

**Issue by iandundas** [ReactiveKit/ReactiveKit#45]
There are quite a few operators that exist on Operation only, currently (`scan`, `reduce`, `take`, etc), and it would be useful to have them also implemented more generally for all Stream types.

**Comment by iandundas** [comment]
#44

**Comment by srdanrasic** [comment]
I agree, but this requires a larger effort and has broader impact. Need to make Stream completable first. I hope I'll be making that update in following weeks.

**Comment by iandundas** [comment]
Cool - will try to help as well. Just opening as a marker for potential future work.

**Comment by srdanrasic** [comment]
Done in v2. Thank you! :)
