### ISSUE TITLE
Advice on avoiding deadlocks?

### ISSUE THREAD

**Issue by iandundas** [ReactiveKit/ReactiveKit#46]
I'm running into deadlocks at `Queue.sync()`, usually related to either trying to setup two-way bindings or when feeding a result back into a chain. For example, here I want to ensure that `endDate` is never earlier than `startDate`: 

```swift
let startDate = ActiveStream<NSDate>()
endDate = ActiveStream<NSDate?>()

combineLatest(startDate, endDate).map { startDate, endDate -> NSDate? in
    guard let endDate = endDate else {return nil}

    if endDate.isEarlierThanDate(startDate) || endDate.isEqualToDateIgnoringTime(startDate){
        return startDate.dateByAddingDays(1)
    }
    return endDate
}.distinctOptional().bindTo(endDate)
```

It's not an infinite loop, because whenever I pause execution the debugger is just parked at `Queue.sync()` (and if I put a breakpoint log there, I can see it's not being called repeatedly).

If I try to be specific about the context that it should use, it still doesn't help:

```swift
startDate.combineLatestWith(endDate).switchTo(ImmediateExecutionContext).map { startDate, endDate -> NSDate? in
    guard let endDate = endDate else {return nil}
    
    if endDate.isEarlierThanDate(startDate) || endDate.isEqualToDateIgnoringTime(startDate){
        return startDate.dateByAddingDays(1)
    }
    return endDate
}.distinctOptional().bindTo(endDate, context: ImmediateOnMainExecutionContext)
```

I can get it to work in an `observe`, but only if I specifically call `.next` asynchronously, i.e.: 

```swift
combineLatest(startDate, endDate).observe { [weak self] startDate, endDate in
    guard let strongSelf = self else {return}
    guard let endDate = endDate else {return}
    
    if endDate.isEarlierThanDate(startDate) || endDate.isEqualToDateIgnoringTime(startDate){
        Async.main{ // prevents deadlock
            strongSelf.endDate.next(startDate.dateByAddingDays(1))
        }
    }
}
```

I'd appreciate any pointers to either what am I doing wrong or another approach for tackling this,

Cheers

**Comment by srdanrasic** [comment]
This should be fixed in v2.
