### ISSUE TITLE
Animations on bounded TableView

### ISSUE THREAD

**Issue by ramirez** [ReactiveKit/ReactiveKit#47]
Hi, 

I'm working with a tableView bound to an observable collection. The animation parameter is set to true and I'm doing ```myObsCol.moveItemAtIndex(idx1 , toIndex: idx2 )```. The animation I'D expect is both getting visually swapped, but they just disappear and reappear in their new locations. Any ideas on how to solve this problem?

Thx!

LEo

**Comment by srdanrasic** [comment]
Bindings are not part of Bond framework.
