### ISSUE TITLE
Rationale of the new names in 2.0 beta?

### ISSUE THREAD

**Issue by ramirez** [ReactiveKit/ReactiveKit#53]
Hi Srdan,

I was going over the migration guide for 2.0 and wondered about the new names for the common entities in ReactiveKit. It seems that for some of the new naming, you moved away from the naming used in other reactive frameworks. Would you care to give us some hints about the rationale you used for the new names?

Thanks!

LEo

**Comment by srdanrasic** [comment]
Hah, I thought it was the other way round :) Main reason is avoiding confusion. Let's see how things look now:

ReactiveKit | RxSwift | ReactiveCocoa | ReactKit | Interstellar
---------------|------------|----------------------|-------------|----------------
Stream | ~~Driver~~ | - | - | -
Operation | Observable | Signal/SignalProducer | Stream | Signal
Property | Variable | Property | - | -
CollectionProperty | - | - | - | -
PushStream | - | - | - | -
PushOperation | PublishSubject | - | - | -
ExecutionContext | Scheduler | Scheduler | - | - | -

So, what I was previously calling _Observable_ is what Rx calls Variable and ReactiveCocoa calls _Property_, and what Rx means by _Observable_ ReactiveKit implements as _Operation_ and _Stream_. There are many resources available online on those frameworks and it would be confusing if we used same terminology for different concepts. Using different terminology for same concepts is acceptable, on the other hand.

**Comment by ramirez** [comment]
Makes sense, Thanks a lot!
