### ISSUE TITLE
'NOT','OR' operation support?

### ISSUE THREAD

**Issue by anddygon** [ReactiveKit/ReactiveKit#56]
I love this kit so much, Thank you for your effort。 
we often meet such requirements， two buttons A and B，the state of them is：if A selected B must Normal，if B selected A must be Normal. 
In ReactiveCocoa i can achieve easily, but i can't find similar operation In ReactiveKit .

**Comment by srdanrasic** [comment]
Thanks @anddygon! I see a couple of ways to do that, but could you detail or post a link to what exactly are you referring to?

**Comment by anddygon** [comment]
My requuirements is: two buttons A and B，the state of them is：if A selected B must Normal，if B selected A must be Normal.
In ReactiveCocoa i can bind A.rac_selected.not.bindTo(b.rac_selected)

**Comment by srdanrasic** [comment]
You can very easily implement `not` by yourself:

```swift
extension StreamType where Element: BooleanType {
  func not() -> Stream<Bool> {
    return map { !$0 }
  }
}
```

It would be same for `OperationType`. I don't think I've understood how `or` should function. I'll think about providing these by default.
