### ISSUE TITLE
Deadlock / Loop protection in 2.0 beta

### ISSUE THREAD

**Issue by rsaarloos** [ReactiveKit/ReactiveKit#58]
Hi,

I have been working for a while now with ReactiveKit, but a couple of days ago I upgraded my code to work with the new 2.0 beta. Unfortunately I'm running in quite a few crashes due to infinite loops and deadlocks. Caused by looped behaviour and two-way bindings.

Before I understood there was a protection mechanism that prevented these issues, but it seems with 2.0 beta this is not in play anymore. Especially for the two-way bindings this seem to be quite an issue in my project.

Any thoughts on this?

**Comment by srdanrasic** [comment]
Hi @rsaarloos, thanks for the feedback. All the changes have probably broken few things and that's why I'm still keeping it in beta. I'm currently writing unit tests and fixing any issues I find for next beta release. Hopefully I'll have that in next few days. 

If you could pinpoint what exactly is causing problem for you I could fix it faster. 

Thanks,
Srdan

**Comment by rsaarloos** [comment]
Hi @srdanrasic I will check what I can do, although my knowledge of the inner workings of ReactiveKit is very limited.

I created an example project here: https://github.com/rsaarloos/reactivekit-two-way-binding-example that provides an example of the two way binding that is used in my project (it will currently crash on any change).

**Comment by srdanrasic** [comment]
Thanks @rsaarloos, that should ne enough. I'll prioritize that issue.

**Comment by srdanrasic** [comment]
Hi @rsaarloos, please try `v2.0.0-beta3` and check if it solves your issues. Thanks!

**Comment by rsaarloos** [comment]
Hey @srdanrasic, this fix seems to resolve the issues I was having. Many thanks, really appreciate the quick help here! Will close the issue.

**Comment by srdanrasic** [comment]
Sure and thank you for pointing this out! If you encounter any more issue feel free to open another ticket/s.
