### ISSUE TITLE
@warn_unused_result for observe and observeNext

### ISSUE THREAD

**Issue by rsaarloos** [ReactiveKit/ReactiveKit#60]
In 2.0 beta the compiler provides a warning when you do not use the result of an `observe` or `observeNext` operation. Most of the time I do not handle the resulting disposable as the observers are automatically disposed when the class where they are declared in is deallocated. Is this a correct way of working, and if so should we then have these warnings?

**Comment by srdanrasic** [comment]
Releasing a property that holds the stream does not necessarily mean that the stream will be disposed. Consider following:

```swift
var timer: Stream<Int>! = .interval(1, queue: Queue.main)

timer.observeNext { t in
  print(t)
}

timer = nil
```

If you run it, you'll see that it continues printing numbers even though stream has been released. It depends on how the producer is defined, but in most cases it's some asynchronous task executing on another thread and sending events to your observer. Only way to cancel it is by disposing it.

Not observing Property would not cause such issue, but as we cannot assume that in general, a good practice is to always dispose the observation.

**Comment by iandundas** [comment]
So I guess what you're saying is that:
- each class should generally have a disposeBag
- we add disposables (returned by creating an observation with `observeNext` etc) to this disposeBag
- these observations will be implicitly disposed with the deallocation of the disposeBag (when the class object is deallocated)

**Comment by srdanrasic** [comment]
That's right @iandundas.

**Comment by iandundas** [comment]
Cool, makes sense and is good to be explicit about these the lifecycle. Nice!
