### ISSUE TITLE
RxSwift vs ReactiveKit. Migration guide from RxSwift -> ReactiveKit

### ISSUE THREAD

**Issue by astrokin** [ReactiveKit/ReactiveKit#61]
Been an intermediate reactive programming developer with RxSwift and ReactiveCocoa (only for obj-c) it would be great to have some guide wich can show the main difference with ReactiveKit.
ReactiveKit looks pretty and another cool thing to have is migration guide from RxSwift since generic idea and even syntax look similar.

**Comment by srdanrasic** [comment]
Good idea :)

**Comment by mingyeow** [comment]
@srdanrasic  i am noticing a lot of small but critical differences in how RK is designed compared to RXSwift/RXCocoa. For example, breaking out failable streams into its own types, having reactive delegates, and a lot of the smaller details. 

You have elaborated on them on and off, but i am curious to understand in more detail more of the thinking contrasting how other swift FRPs are doing it, and how you are thinking about it.
