### ISSUE TITLE
Duplicated code between Operation and Stream

### ISSUE THREAD

**Issue by jechol** [ReactiveKit/ReactiveKit#63]
There are bunch of dup code between Operation.swift and Stream.swift.

I tried to remove dup code by declaring Stream as Operation with NoError, but swift compiler has a bug that blocks this change. What I tried is as below,

```swift
public enum NoError: ErrorType { // No instance of this type is ensured by compiler.
}

/// Represents a stream event.
public protocol StreamEventType: OperationEventType {
}

public extension StreamEventType {
    public typealias Error = NoError
}
```

There might be a reason you have duplicated the code. Could you explain?

**Comment by srdanrasic** [comment]
Ah, Swift is not yet there :) We'd need stuff like Higher Kinded Types (https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20151214/002736.html) to make code even more compact.

Currently, although most of the code of Stream and Operation is similar, it's trivial because it's mostly non-functional wrapper methods over base RawStream where most of the logic lives.

Hope we'll have ability to make it even better in future.

**Comment by jechol** [comment]
I'm trying to remove dup by changing OperationEvent and StreamEvent to class (rather than Enum).

When done, StreamEvent<T> will be subclass of OperationEvent<T, NoError>,
so functions that take OperationEvent<T, E> can accept Stream<T>.

How do you think?

Is there any reason that Event should be value type?

**Comment by srdanrasic** [comment]
What is the benefit of functions that take OperationEvent<T, E> can accept StreamEvent<T>?

**Comment by jechol** [comment]
@srdanrasic More maintainable code and framework size.
There are already differences that should not be.

For example, [`just`, `sequence`, `completed`, `never` function in Stream returns SimpleDisposable](https://github.com/ReactiveKit/ReactiveKit/blob/master/Sources/Stream.swift#L178), whereas [Operation's same functions returns NotDisposable](https://github.com/ReactiveKit/ReactiveKit/blob/master/Sources/Operation.swift#L244).

And, I think `OperationEvent` and `StreamEvent` seems generalisation and specialisation, rather than same level. So `Event` and `SafeEvent` might be more proper name. (also `Stream` and `SafeStream` for `Operation` and `Stream`.)

I think these breaking changes should be considered before you remove beta.

How do you think?







And I think StreamEvent and OperationEvent names are somewhat misleading.

**Comment by srdanrasic** [comment]
I share your desire to reduce code duplication, but unfortunately it's impossible without sacrificing value semantics, performance and some other stuff.

I hope we'll be able to that next year when I hope Swift introduces Higher Kinded Types support. With HKT we would be able to define common implementation of most operators on top-level `StreamType` protocol in extensions. We will be able to deprecate `RawStream` and do something like

```swift
extension StreamType {
  func map<T>(transform: Event.Element -> U) -> Self<Event<T>> {
    ...
  }
```

that will then provide map to both Stream and Operation - something currently impossible without lifting.
