### ISSUE TITLE
[Proposal] Change event types to class from enum.

### ISSUE THREAD

**Issue by jechol** [ReactiveKit/ReactiveKit#67]
[As I said before](https://github.com/ReactiveKit/ReactiveKit/issues/63), existence of two event type `OperationEvent` and `StreamEvent` have introduced most of code dup in ReactiveKit.

I agree that `OperationEvent` and `StreamEvent` are semantically value type.
But we cannot effectively accept both types as input parameter with `EventType` due to its associated type `Element` (and `Error` for `OperationEvent`). And that enforces two version of same function for each type.

If we change `enum` to `class` and make `StreamEvent<T>` as subclass of `OperationEvent<T, NoError>`, we can remove all the duplicated functions. (No instance of `NoError` is ensured by compiler)

```
enum NoError: ErrorType { // Cannot instantiate this type because it has no case
}

class OperationEvent<T, Error> { .... }

class StreamEvent<T>: OperationEvent<T, NoError> {
  // Yay! Empty class body!!!
}

class Operation<T, Error> { ... }

class Stream<T>: Operation<T, NoError> {
  // Yay! Empty class body again!!!
}

extension Operation {
   func map<U>(transform: Element -> U) -> Operation<U, Error> {
     // Yay! Now this works for both Operation and Stream!
   }
}
```

Effects on client code are minimal.
Changing enum to class will disable only usage of `switch` pattern matching, and it only occurs for `func observe(observer: Event -> Void)`.

Most of client code use `func observeNext(observer: Event.Element -> Void)`, which will not be affected.

And pattern matching for `EventType` should be discouraged, because it depends on implementation detail, not `EventType` protocol.

If you agree, I can do the work.

**Comment by srdanrasic** [comment]
I don't think Stream should be a subclass of Operation because Stream has only a subset of operators of Operation. For example you cannot do `flatMapError` on a Stream, but if you make it a subclass it would be allowed.

It could be possible to implement Operation as a Stream of StreamEvent<OperationEvent<T, E>>, but that has its own issues I also don't like it idea of losing value semantics of Stream and Operation type.

There are also implementation differences in some methods regarding error handling.

**Comment by jechol** [comment]
It's possible to make `Operation.flatMapError` to fail by `fatalError()`.

Error handling difference can be ignored because Stream cannot emit Failure.

**Comment by srdanrasic** [comment]
Ah, no :) Main reason behind separating Stream and Operation, i.e. non-failable and failable streams, is to provide compile-time guarantee that errors are handled. When working with ReactiveKit, goal should be to use Stream by default, and to use Operation only for tasks that can fail. All Operations should be then converted to Streams by handling errors before binding them to UI or doing similar action actions.

**Comment by jechol** [comment]
Ah.. I didn't understand rationale behind it. It's clear now.

**Comment by Audioy** [comment]
I think @srdanrasic 's comment should be introduced in the documentation. It makes the difference between Stream and Operation much clearer indeed!
