### ISSUE TITLE
ProtocolProxy returning different results to equivalent delegate callback

### ISSUE THREAD

**Issue by iandundas** [ReactiveKit/ReactiveKit#74]
Hey, here is some sample code showing what I mean. Basically, the Proxy version should output the same result as received by the raw `CLLocationManagerDelegate` callback. For some reason, while the delegate callback receives an `[CLLocation]` of size==1, the Proxy version returns an empty array instead.

The output is:

> location from proxy: []
> location direct from delegate: [<+52.37529000,+4.88390000> +/- 5.00m (speed -1.00 mps / course -1.00) @ 5/31/16, 10:03:17 AM Indochina Time]

```swift 
class DemoProxyDifferences: NSObject, CLLocationManagerDelegate{
    
    private let bag = DisposeBag()
    
    let locationManagerUsingDelegates = CLLocationManager()
    let locationManagerUsingProxy = CLLocationManager()
    
    override init(){
        super.init()
        locationManagerUsingDelegates.delegate = self
        
        startDelegateLocationManager()
        startProxyLocationManager()
    }
    
    func startDelegateLocationManager(){
        locationManagerUsingDelegates.startUpdatingLocation()
    }
    
    func startProxyLocationManager(){
        
        // Updating Locations:
        let didUpdateLocationsSelector = #selector(CLLocationManagerDelegate.locationManager(_:didUpdateLocations:))
        
        let delegateProxy = locationManagerUsingProxy.rDelegate
        delegateProxy.streamFor(didUpdateLocationsSelector, map: { (manager: CLLocationManager, locations: [CLLocation]) -> [CLLocation] in
            return locations
        }).observeNext { locations in
            print("location from proxy: \(locations)")
        }.disposeIn(bag)
        
        locationManagerUsingProxy.startUpdatingLocation()
    }
    
    // MARK: CLLocationManagerDelegate
    func locationManager(manager: CLLocationManager, didUpdateLocations locations: [CLLocation]) {
        print("location direct from delegate: \(locations)")
    }
}
```

**Comment by iandundas** [comment]
(v2.0.3)

**Comment by iandundas** [comment]
Ah I get it - it's because I was using a Swift array type in my callback. So, the following works:

```swift
delegateProxy.streamFor(didUpdateLocationsSelector, map: { (manager: CLLocationManager, locations: NSArray) -> [CLLocation] in
    if let cllocations = locations as? [CLLocation]{
        return cllocations
    }
    return [] // or fatalError, or nil, or whatever's appropriate.
})
```

Glad to have found the fix - would it be possible to make it crash (or log a warning perhaps) here instead of passing the empty array (to make it more obvious to others)?

**Comment by srdanrasic** [comment]
Ah, the delegates :) I'm unhappy with the requirement of using ObjC types. I'm working on a solution that should work with Swift bridged types - hopefully it does.

As for your example, I think you're safe to just do forced cast (`return locations as! [CLLocation]`). `didUpdateLocations:` will always return NSArray, and NSArray can always be casted to right [T].

**Comment by iandundas** [comment]
Cool sounds good, will look out for it
