### ISSUE TITLE
Disposing in ReactiveKitUI

### ISSUE THREAD

**Issue by mingyeow** [ReactiveKit/ReactiveKit#75]
Migrating from Bond to RK, a little confused about when/how to dispose. I am using reactivekit ui, and i am not sure when to dispose of the stream. Apparently, when i chain the observe function to the dispose function, the tap will stop working. 

See below for the various combinations i have tried.

What is the suggested method here?

```
    import ReactiveKit
    
    class LaunchScreenViewController: UIViewController {
    
      @IBOutlet weak var startButton: UIButton!
    
      override func viewDidLoad() {
          super.viewDidLoad()
          
          startButton.enabled = true

          // this warns because of the @warn_unused_result definition
          startButton.rTap.observeNext{ _ in
            print ("xxxx")
          }

          // is this to encourage usage of dispose when viewcontroller gets disposed? feels redundant since it will be disposed after the vc is disposed
          let x = startButton.rTap.observeNext{ _ in
            print ("xxxx")
          }.isDisposed

          // feels redundant
          startButton.rTap.observeNext{ _ in
            print ("xxxx")
          }.isDisposed

          // rtap will not work anymore
          startButton.rTap.observeNext{ _ in
            print ("xxxx")
          }.disposeIn(DisposeBag()
    
      }
    
    }

```

**Comment by srdanrasic** [comment]
Hi @mingyeow, you were almost there :)

`DisposeBag` will dispose all disposables when it's deallocated. You're doing `.disposeIn(DisposeBag())` so it deallocates immediately. You need to have it as a property.

```swift
class A {
  let disposeBag = DisposeBag()
  ...
  ...observerNext { _ in }..disposeIn(disposeBag)
  ...
}
```

If you're observing in a subclass of ObjC class, like UIViewController, you can do `.disposeIn(rBag)`. `.rBag` is an NSObject extension provided by ReactiveKit. 

Hope this helps!

**Comment by srdanrasic** [comment]
I just updated the documentation to make this clear: https://github.com/ReactiveKit/ReactiveKit#-cancellation.

**Comment by frankschlegel** [comment]
I was writing a longer explanation, but @srdanrasic was faster. 😊
But here it is anyways:

In general you have to ask yourself who is holding a reference to the binding you create with `observeNext` or `bind`. When the last reference is gone, the binding will no longer exist.

For `bind`, the binding target (the parameter of `bind()`) will hold a reference to the binding. When the target is gone, so is the binding.

However, for `observe` you specify a block that becomes the "target" of the binding. Somebody else needs to manage the reference to that binding in this case. Here `DisposeBag`s come in. With `disposeIn()` you can specify a bag that should hold a reference to the binding. When the bag is disposed or destroyed, all references to bindings it holds are also disposed. You can use that to specify which object should hold a reference to the binding you create with `observeNext` by putting it in a bag associated with that object.
As @srdanrasic said all Obj-C objects already have a `DisposeBag` attached to them (`rBag`).

In your case you probably want the bindings to disappear when the view controller gets deleted. The easiest way to achieve that is to put them in the view controller's bag `.disposeIn(rBag)`.

Hope that helps!

**Comment by mingyeow** [comment]
Guys, This is super helpful, thanks! now i understand it much better. 

@srdanrasic: Quick qn: what is the motivation for the warning, since it did not exist in bond? was it to make sure even beginners (like yours truly) know about dispose? :D

@frankschlegel great answer, thanks! i was confused between the observe target block and the reference to the binding. your answer cleared it up.
