### ISSUE TITLE
Compilation error with version 2.0.+

### ISSUE THREAD

**Issue by trupin** [ReactiveKit/ReactiveKit#77]
Hi,

Since [this commit at the line 26](https://github.com/ReactiveKit/ReactiveKit/blob/50e4c83bfaee06758003a711558add9735dcdf18/ReactiveKit/ReactiveKit.h#L26), I get this error 
`Include of non-modular header inside framework module` at build time.

I tried to build a blank project with only ReactiveKit as a dependency in my podfile and the error persists. It works fine with the latest beta though.

I am using Xcode 7.3.1

Regards

**Comment by srdanrasic** [comment]
Hi @trupin, are you using CocoaPods and do you have the latest version of it? There was the same issue reported in #72 and it was fixed by CocoaPods update.

**Comment by trupin** [comment]
I am indeed using the version 0.39.0 of cocoapods. I actually cannot use the versions 1.+ since I use some dependencies which are not ready for it yet.

On this project I am stuck with the beta version of ReactiveKit because of this.

Do you think it's doable to make the release compatible with cocoapods v0.39.0 ?

**Comment by trupin** [comment]
I finally found a way to update to cocoapods v1.0.1 and everything is working as expected now.

Thanks a lot for your help, and this awesome library !
