### ISSUE TITLE
Add oldCollection property to CollectionChangeset

### ISSUE THREAD

**Issue by lmcd** [ReactiveKit/ReactiveKit#78]
When items are deleted from a collection, it's not currently possible to determine which items were removed by looking at the changeset. We have access to the indices in `deletes`, but these refer to items that don't exist anymore.

An `oldCollection` property on `CollectionChangeset` would be useful

**Comment by srdanrasic** [comment]
Hi @lmcd,

There is an operator `zipPrevious` that will zip current event with the previous one. So in the observeNext you can get a pair of CollectionChangesets.

```swift
array.zipPrevious().observeNext { (oldChanges, newChanges) in
  print(oldChanges?.collection)
  print(newChanges.collection)
}
```

Can this solve your problem?

**Comment by lmcd** [comment]
Perfect, thanks!
