### ISSUE TITLE
How to force operation to work on a background thread?

### ISSUE THREAD

**Issue by iandundas** [ReactiveKit/ReactiveKit#79]
Hey,

How to force a Stream or an Operation to carry out work on a background thread? I know I can determine on which context results are delivered to the observer (`.observeIn(Queue.main.context)` by default), but sometimes I want to do the hard stuff in the background then deliver on the main. My homemade Operation seems to start work on the main thread.

Thanks,
Ian

**Comment by srdanrasic** [comment]
Hi @iandundas, the operator for that would be `executeIn`.

**Comment by iandundas** [comment]
Ah, perfect! Shit, I did look, I swear it.. 😅

**Comment by srdanrasic** [comment]
Hah, no worries 😃
