### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by adamrowell** [ReactiveKit/ReactiveKit#80]
Great package -- I've been using it for a while.  It would be really useful to have official Linux support and provide a package.

**Comment by srdanrasic** [comment]
Hi @adamrowell,

I have been working on the port to Swift 3 and it is already compilable on Linux. I just pushed the branch _swift-3_ if you'd like to try. Unfortunately, libdispatch is not yet available on Linux so we don't have full functionality yet - there is some dummy code in _Threading.swift_ at the moment.

Let's hope libdispatch will be part of first Swift 3 developer preview release that's coming this week (today?).

**Comment by n8gray** [comment]
Hi, any update on this now that libDispatch is officially supported on Linux?

**Comment by srdanrasic** [comment]
Hi @n8gray,

It was actually working on Linux all along, but there were some issues with tests. Those are now fixed so I guess we can declare Linux support official. Check out v3.8.3.

Thanks!

**Comment by n8gray** [comment]
awesome!
