### ISSUE TITLE
Swift 2.3 - Carthage issue

### ISSUE THREAD

**Issue by iandundas** [ReactiveKit/ReactiveKit#82]
Compiling latest ReactiveKit (2.1) 

    carthage update --no-use-binaries --platform iOS

produces the following, when Xcode 8 beta 1 is set as default Xcode (`xcode-select`): 

```
--- xcodebuild: WARNING: Unable to open project file '/Users/ian/AppsDev/tacks/tacks_ios/Carthage/Checkouts/ReactiveKit/ReactiveKitPlayground.playground' in workspace '/Users/ian/AppsDev/tacks/tacks_ios/Carthage/Checkouts/ReactiveKit/ReactiveKit.xcworkspace'.
```

This is when building for iOS.

**Comment by iandundas** [comment]
I just tried compiling a fork where the 2.3 Migrator had been run ("no changes needed") and the Playground removed from the workspace, but unfortunately that exposed a bunch more compile errors.

```The following build commands failed:
	CompileSwift normal arm64 /Users/ian/AppsDev/tacks/tacks_ios/Carthage/Checkouts/ReactiveKit/Sources/RawStream.swift
	CompileSwift normal arm64 /Users/ian/AppsDev/tacks/tacks_ios/Carthage/Checkouts/ReactiveKit/Sources/Result.swift
	CompileSwift normal arm64 /Users/ian/AppsDev/tacks/tacks_ios/Carthage/Checkouts/ReactiveKit/Sources/Property.swift
	CompileSwift normal arm64 /Users/ian/AppsDev/tacks/tacks_ios/Carthage/Checkouts/ReactiveKit/Sources/ProtocolProxy.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(5 failures)```

**Comment by srdanrasic** [comment]
Why new stuff always breaks existing 😠  I'll get Xcode 8 these days and hopefully fix it if the issue is on our side.

**Comment by iandundas** [comment]
👍🏻 thanks

**Comment by srdanrasic** [comment]
Hi @iandundas, looks like Xcode 8 is using Swift 3 by default. Can you try running following:

```
TOOLCHAINS=com.apple.dt.toolchain.Swift_2_3 carthage update --no-use-binaries --platform iOS
```

It will make xcodebuild use Swift 2.3 and it should work.

**Comment by iandundas** [comment]
I think that worked - thanks! (well I mean it didn’t work because then Realm didn’t support Swift 2.3. .. But I think it worked yeah ;) )
