### ISSUE TITLE
Track moves in CollectionChangeset

### ISSUE THREAD

**Issue by lmcd** [ReactiveKit/ReactiveKit#85]
It's very cumbersome given a `CollectionChangeset` to arrive at the original `from` and `to` indices of a `moveItemAtIndex` operation.

Is there any good reason there isn't a `moves` property in `CollectionChangeset`?

**Comment by srdanrasic** [comment]
This feature is now implemented and moved to Bond framework that's now built on top of ReactiveKit :)
