### ISSUE TITLE
[Feature] `zipLatest`

### ISSUE THREAD

**Issue by jechol** [ReactiveKit/ReactiveKit#93]
Assume that there is a text field and a button, and we want to do something when button is tapped.

`combineLatest(textField.rText, button.rTap)` is not working this case.

Something like `zipLatest(textField.rText, button.rTap)` would be useful.

See http://stackoverflow.com/questions/38190722/does-my-ziplatest-operator-already-exist

**Comment by jechol** [comment]
I found `zipLatest` is also not working in the case...

-- "email"
--                Tap   -    Tap

second tap will not fire with `zipLatest`.

I am considering `Property`, I don't like reference `Property.value` because it seems same before Rx.

What is best solution for in this case?

**Comment by srdanrasic** [comment]
Hi @jechol,

I think that what you're looking for is called `withLatestFrom`.

```swift
button.rTap.withLatestFrom(textField.rText)
```

It'll combine a button tap with the latest value form text field at the moment of tap.

**Comment by jechol** [comment]
@srdanrasic Exactly what I want. Thanks!
