### ISSUE TITLE
Combining Bool Streams into one Stream

### ISSUE THREAD

**Issue by prefect42** [ReactiveKit/ReactiveKit#94]
I am trying to create a Stream that will signal me that all non optional text fields in a registration are valid.
Every input field has a stream signaling wether the field is filled out correctly and has been validated.

How do I combine all those Stream<Bool> into one Master Stream<Bool>?

I think I am looking for something like this from RAC:

```
- (RACSignal *)canSubmitSignal {
    return [[RACSignal combineLatest:@[ self.passwordsAreEqualSignal, self.passwordIsLongEnoughSignal, self.emailIsValidSignal, RACAbleWithStart(self.notSubmitting), RACAbleWithStart(self.acceptTerms) ]] map:^(RACTuple *tuple) {
        BOOL allYes = [tuple.rac_sequence all:^(NSNumber *num) {
            return num.boolValue;
        }];
        return @(allYes);
    }];
}
```

Could someone with experience tell me how to accomplish this in ReactiveKit please?

**Comment by srdanrasic** [comment]
It should be quite similar:

```swift
let canSubmit = combineLatest(passwordsAreEqual, passwordIsLongEnough, emailIsValid, ...).map { $0 && $1 && $2 ... }
```

Given that all argument are boolean streams like `Stream<Bool>`.

**Comment by prefect42** [comment]
Excellent thanks!
