### ISSUE TITLE
Suggestion: Tracking Dirty State of Property

### ISSUE THREAD

**Issue by AnthonyMDev** [ReactiveKit/ReactiveKit#97]
I'd like to be able to check and see if a `Property` has ever had it's value changed.

If the value is changed and then changed back to the initial value, then the dirty property should return false. This would mean the initial value of the property would need to be retained though.

A `reset()` method would reset the value to its initial value.
A `commit()` method would set the initial value to the current value.

With this functionality, it believe it would also be relatively simple to use a `Property` with `NSUndoManager`.

As an alternative, we could create a passthrough class similar to `AnyProperty` that would add this functionality, rather than expanding `Property`.

I would be willing to assist in the implementation of this, but I wanted to see if this functionality would be desired in `ReactiveKit` and discuss implementation options.

**Comment by srdanrasic** [comment]
This is interesting feature, but I think it should be implemented as a new type. It would also have a constraint that values are Equatable. I would also not include this in ReactiveKit since I'd like it to be as lightweight as possible.
