### ISSUE TITLE
Binding a stream to collection property

### ISSUE THREAD

**Issue by mingyeow** [ReactiveKit/ReactiveKit#98]
This error occurs: error: cannot invoke 'bindTo' with an argument list of type '(CollectionProperty<Array<Int>>)'

I can do observeNext and replace, but that defeats the purpose slightly. Is there a way to do this?

```
let counterArray = Stream.sequence([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
let va:Property<Array<Int>> = Property([])
//works
counterArray.bindTo(va)

let vac:CollectionProperty<Array<Int>> = CollectionProperty([])
// does not work
counterArray.bindTo(vac)

```

**Comment by srdanrasic** [comment]
This is not supported with ReactiveKit 3.
