### ISSUE TITLE
Text Field binding fails to update on spelling correction

### ISSUE THREAD

**Issue by jefmwols** [ReactiveKit/ReactiveKit#99]
Using a view controller with the below code, type the text "ratz" into the text filed.
Observe that the label will update as you type, as expected.
Now tap the Return key.
The tech filed now contains "rats" while the table still contains "ratz".
The expectation is that the label should have changed to match the text field.

class ViewController: UIViewController {

    @IBOutlet weak var nameTextField: UITextField!
    @IBOutlet weak var nameLabel: UILabel!
    let name = Property<String?>("")
    
    override func viewDidLoad() {
        super.viewDidLoad()
 
        
        nameTextField.rText.bindTo(nameLabel.rText)
        
    }

**Comment by srdanrasic** [comment]
I think this should be fixed in Bond 5 that is now replacing ReactiveUIKit.
